#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.


source ~/python-2.7/activate_virtenv
cd $OPENSHIFT_REPO_DIR/
echo 'Manage syncdb'
python manage.py syncdb --noinput
echo 'Manage migrate'
python manage.py migrate --noinput

cp -R $OPENSHIFT_REPO_DIR/confessiator/media/*  $OPENSHIFT_REPO_DIR/wsgi/static
